// TODO: replace with real menu from client
import type { MenuCategory } from '@/types/menu';

export const menuCategories: MenuCategory[] = [
  {
    id: 'noodles',
    nameHe: 'נודלס',
    nameEn: 'Noodles',
    color: 'coral',
    items: [
      {
        id: 'ramen-tonkotsu',
        nameHe: 'ראמן טונקוצו',
        nameEn: 'Tonkotsu Ramen',
        descriptionHe: 'מרק עשיר, נודלס טריים, ביצה רכה, בצל ירוק',
        descriptionEn: 'Rich broth, fresh noodles, soft egg, scallions',
        price: 62,
        category: 'noodles',
        isPopular: true,
      },
      {
        id: 'pad-thai',
        nameHe: 'פאד תאי',
        nameEn: 'Pad Thai',
        descriptionHe: 'נודלי אורז, ביצה, בוטנים, ליים, נבטים',
        descriptionEn: 'Rice noodles, egg, peanuts, lime, bean sprouts',
        price: 58,
        category: 'noodles',
      },
      {
        id: 'udon-beef',
        nameHe: 'אודון בקר',
        nameEn: 'Beef Udon',
        descriptionHe: 'נודלי אודון עבים, רצועות בקר, ירקות מוקפצים',
        descriptionEn: 'Thick udon noodles, beef strips, stir-fried vegetables',
        price: 68,
        category: 'noodles',
      },
      {
        id: 'dan-dan',
        nameHe: 'דאן דאן',
        nameEn: 'Dan Dan Mian',
        descriptionHe: 'נודלס סצ׳ואנים חריפים, בשר טחון, שומשום',
        descriptionEn: 'Spicy Sichuan noodles, minced meat, sesame',
        price: 56,
        category: 'noodles',
        isNew: true,
      },
    ],
  },
  {
    id: 'dimsum',
    nameHe: 'דימסאם',
    nameEn: 'Dim Sum',
    color: 'yellow',
    items: [
      {
        id: 'gyoza-veg',
        nameHe: 'גיוזה ירקות',
        nameEn: 'Veggie Gyoza',
        descriptionHe: 'כיסונים מטוגנים, ממולאים בירקות וג׳ינג׳ר',
        descriptionEn: 'Pan-fried dumplings, filled with vegetables and ginger',
        price: 38,
        category: 'dimsum',
      },
      {
        id: 'shumai',
        nameHe: 'שומאי בשר',
        nameEn: 'Beef Shumai',
        descriptionHe: 'כיסוני בשר מאודים, שמן שומשום',
        descriptionEn: 'Steamed beef dumplings, sesame oil',
        price: 42,
        category: 'dimsum',
        isPopular: true,
      },
      {
        id: 'xiao-long',
        nameHe: 'שיאו לונג באו',
        nameEn: 'Xiao Long Bao',
        descriptionHe: 'כיסונים ממולאי מרק, זנגביל, חומץ',
        descriptionEn: 'Soup-filled dumplings, ginger, vinegar',
        price: 48,
        category: 'dimsum',
      },
      {
        id: 'wonton-spicy',
        nameHe: 'וונטון חריף',
        nameEn: 'Spicy Wonton',
        descriptionHe: 'כיסוני משי, צ׳ילי שחור, שעועית מותססת',
        descriptionEn: 'Silk wontons, black chili, fermented bean',
        price: 44,
        category: 'dimsum',
        isNew: true,
      },
    ],
  },
  {
    id: 'sushi',
    nameHe: 'סושי ומאקי',
    nameEn: 'Sushi & Maki',
    color: 'green',
    items: [
      {
        id: 'spicy-tuna-roll',
        nameHe: 'רול טונה חריף',
        nameEn: 'Spicy Tuna Roll',
        descriptionHe: 'טונה טרייה, מיונז חריף, שומשום, עטיפה קריספית',
        descriptionEn: 'Fresh tuna, spicy mayo, sesame, crispy wrap',
        price: 54,
        category: 'sushi',
        isPopular: true,
      },
      {
        id: 'salmon-nigiri',
        nameHe: 'ניגירי סלמון',
        nameEn: 'Salmon Nigiri',
        descriptionHe: '4 יחידות, סלמון נורווגי, וואסאבי',
        descriptionEn: '4 pieces, Norwegian salmon, wasabi',
        price: 48,
        category: 'sushi',
      },
      {
        id: 'rainbow-roll',
        nameHe: 'רול קשת',
        nameEn: 'Rainbow Roll',
        descriptionHe: 'אבוקדו, קליפורניה, דגים מעורבים למעלה',
        descriptionEn: 'Avocado, California, mixed fish on top',
        price: 68,
        category: 'sushi',
      },
      {
        id: 'veggie-maki',
        nameHe: 'מאקי ירקות',
        nameEn: 'Veggie Maki',
        descriptionHe: 'אבוקדו, מלפפון, גזר, שומשום',
        descriptionEn: 'Avocado, cucumber, carrot, sesame',
        price: 38,
        category: 'sushi',
      },
    ],
  },
  {
    id: 'buns',
    nameHe: 'באנים',
    nameEn: 'Buns',
    color: 'coral',
    items: [
      {
        id: 'chicken-bao',
        nameHe: 'באו עוף קריספי',
        nameEn: 'Crispy Chicken Bao',
        descriptionHe: 'באן רך, עוף פריך, כרוב מוחמץ, מיונז יפני',
        descriptionEn: 'Steamed bun, crispy chicken, pickled cabbage, Japanese mayo',
        price: 46,
        category: 'buns',
        isPopular: true,
      },
      {
        id: 'beef-bao',
        nameHe: 'באו בקר מעושן',
        nameEn: 'Smoked Beef Bao',
        descriptionHe: 'בקר נמס, בצל מטוגן, רוטב הויסין',
        descriptionEn: 'Melting beef, fried onion, hoisin sauce',
        price: 52,
        category: 'buns',
      },
      {
        id: 'tofu-bao',
        nameHe: 'באו טופו',
        nameEn: 'Tofu Bao',
        descriptionHe: 'טופו קראנץ׳, בוטנים, כוסברה, שמן חריף',
        descriptionEn: 'Crunchy tofu, peanuts, coriander, chili oil',
        price: 42,
        category: 'buns',
        isNew: true,
      },
    ],
  },
  {
    id: 'sides',
    nameHe: 'צדיות',
    nameEn: 'Sides',
    color: 'yellow',
    items: [
      {
        id: 'edamame',
        nameHe: 'אדממה',
        nameEn: 'Edamame',
        descriptionHe: 'פולי סויה מאודים, מלח ים, שמן שומשום',
        descriptionEn: 'Steamed soybeans, sea salt, sesame oil',
        price: 24,
        category: 'sides',
      },
      {
        id: 'spring-rolls',
        nameHe: 'אביב רולז',
        nameEn: 'Spring Rolls',
        descriptionHe: 'עטיפה פריכה, ירקות, רוטב חמוץ-חריף',
        descriptionEn: 'Crispy wrap, vegetables, sweet-sour sauce',
        price: 32,
        category: 'sides',
      },
      {
        id: 'cucumber-salad',
        nameHe: 'סלט מלפפון',
        nameEn: 'Smashed Cucumber',
        descriptionHe: 'מלפפון קצוץ, שום, חומץ אורז, צ׳ילי',
        descriptionEn: 'Smashed cucumber, garlic, rice vinegar, chili',
        price: 28,
        category: 'sides',
      },
    ],
  },
  {
    id: 'drinks',
    nameHe: 'שתייה',
    nameEn: 'Drinks',
    color: 'green',
    items: [
      {
        id: 'lychee-lemonade',
        nameHe: 'לימונדת ליצ׳י',
        nameEn: 'Lychee Lemonade',
        descriptionHe: 'לימונדה עם ליצ׳י ועלי נענע',
        descriptionEn: 'Lemonade with lychee and mint leaves',
        price: 22,
        category: 'drinks',
        isPopular: true,
      },
      {
        id: 'matcha-latte',
        nameHe: 'מאצ׳ה לאטה קר',
        nameEn: 'Iced Matcha Latte',
        descriptionHe: 'מאצ׳ה טהור, חלב שקדים, קרח',
        descriptionEn: 'Pure matcha, almond milk, ice',
        price: 24,
        category: 'drinks',
      },
      {
        id: 'thai-tea',
        nameHe: 'תה תאילנדי',
        nameEn: 'Thai Iced Tea',
        descriptionHe: 'תה שחור קלאסי, חלב קוקוס',
        descriptionEn: 'Classic black tea, coconut milk',
        price: 22,
        category: 'drinks',
      },
      {
        id: 'yuzu-soda',
        nameHe: 'סודה יוזו',
        nameEn: 'Yuzu Soda',
        descriptionHe: 'סודה מוגזת עם יוזו ויאנג׳ר',
        descriptionEn: 'Sparkling soda with yuzu and ginger',
        price: 20,
        category: 'drinks',
        isNew: true,
      },
    ],
  },
];
